services:
  web:
    build: .
    ports:
      - "${PORT}:5000"
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  redis-data:
    external: true 
